### ISSUE TITLE
Survivality 1.2.1-1.2.2 crash w/ Regions Unexplored mod

### ISSUE THREAD

**Issue by Emerald131** [jack-zisa/survivality#3]
After some trial & error, I've discovered that I get a  game crash when running this with the Regions Unexplored mod specifically (and possible Areas Undefined as well). TerraBlender works fine on its own.

Here is the crash report with Regions Unexplored enabled: [crash-2023-05-03_21.05.40-client.txt](https://github.com/jack-zisa/survivality/files/11392872/crash-2023-05-03_21.05.40-client.txt)

**Comment by jack-zisa** [comment]
This is a simple fix. I'll release a new version asap.

**Comment by jack-zisa** [comment]
I released forge version 1.2.3 which addresses this bug. Let me know if it works!

**Comment by Emerald131** [comment]
Same crash still occurs. here's the new crash report:  [crash-2023-05-03_23.26.05-client.txt](https://github.com/jack-zisa/survivality/files/11394212/crash-2023-05-03_23.26.05-client.txt)

**Comment by jack-zisa** [comment]
Second attempt submitted to CurseForge & Modrinth. The snowy leaves feature wasn't working with Forge anyway so I just removed it until further notice. This version should work but please let me know!

**Comment by Emerald131** [comment]
It's working fine now. No conflict with any of my other mods, these quality of life changes really make the game more fun!
